name: pensa_dev
channels:
  - conda-forge
  - defaults
dependencies: 
  - python==3.10
  - scipy
  - numpy
  - pandas
  - matplotlib
  - MDAnalysis==2.8
  - deeptime
  - biotite
  - pip
  - pytest
  - twine
  - build
  - sphinx
  - sphinx_rtd_theme

